src/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contestant__c.object
<CustomObject>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Driver</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
            <filterItems>
                <field>Driver__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only Drivers who&apos;s status is active are permitted.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Driver__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <referenceTo>Race__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Driver__c.object
<CustomObject>
    <fields>
        <fullName>DriverId__c</fullName>
        <label>Driver Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Race__c.object
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RaceData__c.object
<CustomObject>
    <fields>
        <fullName>Race__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Race</label>
        <referenceTo>Race__c</referenceTo>
        <relationshipLabel>Race Data</relationshipLabel>
        <relationshipName>RaceData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Race Data</label>
    <nameField>
        <displayFormat>RDID-{00000000}</displayFormat>
        <label>Race Data Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RaceServiceImpl.cls
public class RaceServiceImpl implements IRaceService {
    
    public Map<Id, List<RaceService.ProvisionalResult>> calculateProvisionResults(Set<Id> raceIds) {           
        throw new RaceService.RaceServiceException('Not implemented');
    }

    public void applyRaceResults(Map<Id, List<RaceService.ProvisionalResult>> provisionalResultsByRaceId) {
        throw new RaceService.RaceServiceException('Not implemented');
    }

    public void awardChampionshipPoints(Set<Id> raceIds) {
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        // Query Races and contestants and bulkify list of all contestants
        RacesSelector racesSelector = (RacesSelector) Application.Selector.newInstance(Race__c.SObjectType);        
        List<Contestant__c> contestantsList = new List<Contestant__c>();
        for(Race__c race : racesSelector.selectByIdWithContestants(raceIds)) {
            contestantsList.addAll(race.Contestants__r);            
        }
        
        // Delegate to Contestant Domain class
        Contestants contestants = (Contestants) Application.Domain.newInstance(contestantsList);
        contestants.awardChampionshipPoints(uow);

        // Commit work
        uow.commitWork();
    }
    
	public String generateSummaryAsCSV(Set<Id> raceIds)
	{
		// Query summaries via custom selector method
		Map<Id, List<ContestantsSelector.Summary>> summariesByRaceId = 
			new ContestantsSelector().selectByRaceIdWithContestantSummary(raceIds);
		// Construct CSV output (note this is not a formal implementation of the CSV spec)
		String csvOutput = '';
		for(Id raceId : summariesByRaceId.keySet())
			for(ContestantsSelector.Summary raceContestantSummary : summariesByRaceId.get(raceId))
				csvOutput+= String.join(
					new Object[] { 
							raceContestantSummary.Season,
							raceContestantSummary.Race,
							raceContestantSummary.Position,
							raceContestantSummary.Driver,
							raceContestantSummary.Team,
							raceContestantSummary.Car
						} , ',') + '\r\n';
		return csvOutput;
	}
	
    public Map<Id, Integer> addDrivers(Map<Id, List<Id>> driversByRaceId) {
        
        // TODO: Provide a means to determine drivers current car for the season
        List<Car__c> cars = new CarsSelector().selectAll();
        if(cars.size()>0) {
            throw new RaceService.RaceServiceException('Must have at least one Car record in the system');          
        }        
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
 
        // Create Contestant__c records for each Driver for the given Race
        for(Id raceId : driversByRaceId.keySet()) {
            for(Id driverId : driversByRaceId.get(raceId)) {
                Contestant__c contestant = new Contestant__c();
                contestant.Race__c = raceId;
                contestant.Driver__c = driverId;
                contestant.Car__c = cars[0].Id;
                uow.registerNew(contestant);                
            }            
        }       
 
        // Commit work
        uow.commitWork();
        
        return null;
    }	
    
	public Id runProcessDataJob()
	{
		// TODO: Implement concurrency check and scope config (via custom setting)
		return Database.executeBatch(new ProcessRaceDataJob(), 2000);	
	}    
    
	public void processData(Set<Id> raceDataIds)
	{
		// Query Race Data records and update with Contestant relationship
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		for(RaceData__c raceData : 
				(List<RaceData__c>)
					Application.Selector.selectById(raceDataIds))
		{
			// Associate Race Data record with a Contestant via Unique Id
			raceData.Contestant__r = 
				new Contestant__c(
					RaceDataId__c = 
						Contestants.makeRaceDataId(
							raceData.Year__c, 
							raceData.RaceName__c, 
							raceData.DriverId__c));
			uow.registerDirty(raceData);
		}
		// Update records
		uow.commitWork();
	}
        
	public List<RaceService.AnalysisResult> analizeData(Set<String> raceNames)
	{
		List<RaceData__c> raceData = 
			RaceDataSelector.newInstance().selectByRaceName(raceNames);			
		return null;
	}
}